server:
  port: 8084
spring:
  spring.jpa.defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: razdeepak
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/car
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

